version: "3"
services:
  app:
    build:
      context: fe
      dockerfile: Dockerfile
    container_name: iot-app
    restart: always
    ports:
      - "80:4000"
    network_mode: default
  api:
    build:
      context: be
      dockerfile: Dockerfile
    container_name: iot-api
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    network_mode: default
  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    network_mode: default
    container_name: mongo
networks:
  default:
    external:
      name: bridge